apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: kube-logging
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: inter-node
